theme: jekyll-theme-cayman
title: Hello! Welcome to the Jakob’s homepage!
description: On this site you can find *information* on [my projects as well as my resume] (https://www.linkedin.com/in/jakob-winkler-6924a8a9/).
